#FROM nginx
#COPY ./default.conf /etc/nginx/nginx.conf
#COPY ./default.conf /etc/nginx/conf.d/default.conf
#COPY ./nginx.conf /etc/nginx/nginx.conf
#COPY ./default.conf /etc/nginx/nginx.conf
FROM nginx
COPY default.conf /etc/nginx/nginx.conf
